# Retrieve a Bitwarden item's raw content (single command):
# bw list items --search <TEXT> --pretty

[bitwarden.secrets]
git_email_address = "c358ce27-ec3a-4db4-bc04-b09e012d5d52"

[bitwarden.notes]
work_repos = "e92a4929-e938-40b9-9ac6-b0a601470ecb"
personal_repos = "5a0c64c8-fc70-4bbb-81dd-b0a6014248a5"
shared_repos = "f3311005-ef5c-409f-8a5e-b0a601473b0f"
git_user_path_definition = "fa1e09de-c98e-422a-8c55-b3ef001dd22b"
git_user_a = "79316371-106f-4b8f-8e69-b3ef001e63d1"
git_user_c = "320e65b5-ad3b-46bf-aed6-b3f0002378cd"

[bitwarden.ssh]
devops_a = "5b50fc2c-23f6-4c82-8aa5-b3ef00ff173d"
devops_c = "c1f08c41-db51-4ee2-b7f8-b3f000250aee"