[packages.homebrew]
    to_remove = []
    [packages.homebrew.common]
        tap = [
            "mrkai77/cask"
            ]
        casks = [
            "appcleaner",
            "chatgpt",
            "displaylink",
            "iterm2",
            "linearmouse",
            "loop",
            "logitune",
            "microsoft-edge",
            "msty",
            "obsidian",
            "shottr",
            "updf"
        ]
        formulae = [
            "chezmoi",
            "dockutil",
            "mas",
            "rbw",
            "starship",
            "zsh",
            "zsh-autosuggestions",
            "zsh-syntax-highlighting",
            "zsh-you-should-use"
        ]
    [packages.homebrew.personal_computer]
        tap = []
        casks = [
            "autodesk-fusion",
            "brave-browser",
            "calibre",
            "signal",
            "yubico-authenticator",
            "microsoft-auto-update",
            "microsoft-excel",
            "microsoft-powerpoint",
            "microsoft-word",
            "onedrive",
            "whatsapp"
        ]
        formulae = []
    [packages.homebrew.work_computer]
        tap = []
        casks = [
            "tor-browser",
            "unclack",
            "azure-data-studio"
        ]
        formulae = [
            "",
            ""
        ]
    [packages.homebrew.dev_computer]
        tap = [
            "azure/bicep",
            "hashicorp/tap",
            "qmk/qmk",
        ]
        casks = [
            "bruno",
            "drawio",
            "font-fira-code",
            "font-monaspace",
            "git-credential-manager",
            "github",
            "msty",
            "powershell",
            "visual-studio-code",
            "visual-studio-code@insiders"
        ]
        formulae = [
            "azure-cli",
            "bicep",
            "git",
            "ollama",
            "qmk",
            "hashicorp/tap/terraform",
        ]
    [packages.homebrew.docker_computer]
        tap = []
        casks = ["docker"]
        formulae = []
[packages.mas]
    [packages.mas.common]
        apps = [
            "441258766", # Magnet
            "1352778147" # Bitwarden
        ]
    [packages.mas.personal_computer]
        apps = [
            "1303222628", # Paprika receipe manager
            "1193539993" # Brother Iprint&scan
        ]
    [packages.mas.work_computer]
        apps = [
            "1268962404" # Smart JSON Editor
        ]
    [packages.mas.dev_computer]
        apps = []
    [packages.mas.docker_computer]
        apps = []
